spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://localhost:5432/library
    username: postgres
    password: 123456789
  application:
    name: library-service

server:
  port: 0


eureka:
  instance:
    instance-id: ${spring.application.name}:${random.value}
    prefer-ip-address: true
  client:
    service-url:
      default-zone: ${EUREKA_URI:http://localhost:8761/eureka}
logging:
  config: classpath:log4j2.xml

management:
  tracing:
    sampling:
      probability: 1.0